---
Name: spellcheckroutes
---
SilverStripe\Control\Director:
  rules:
    spellcheck: SilverStripe\SpellCheck\Handling\SpellController

---
Name: spellcheckprovider
---
# Set the default provider to HunSpell
SilverStripe\Core\Injector\Injector:
  SilverStripe\SpellCheck\Data\SpellProvider:
    class: SilverStripe\SpellCheck\Providers\HunSpellProvider

---
Name: spellcheckprocessors
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\RequestProcessor:
    properties:
      filters:
        - '%$SilverStripe\SpellCheck\Handling\SpellRequestFilter'
